### ISSUE TITLE
[tests] Workload tests

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#2689]
These would be tests that exercise the workload, like:

# Template tests
- [ ] #9576
- [x] with no workload installed, a project with `$(IsAspireHost)=true` would fail to build due to missing `aspire` workload
- [x] basic templates can build and run
- [x] Starter template can run (WIP)
- [x] Starter template's included test project works (WIP)
- [x] create+build+run starter template, and run some basic checks including checking the dashboard (WIP)

# Dashboard

- [x] verify all the resources show up (WIP)

# Others
- [x] This is being handled indirectly with playground, and EndToEnd tests. ~~Test per published nuget, to use the nuget and perform some basic validation~~
- [ ] manifest publishing works with `dotnet run`
- [x] default https works on linux
- [x] `ASPIRE_ALLOW_UNSECURED_TRANSPORT`

Future:

**Comment by radical** [comment]
cc @joperezr

**Comment by eerhardt** [comment]
If I was dreaming, we would also have tests that publish an app to Azure. But that is going to take a lot of infrastructure.

> with no workload installed, a project with $(IsAspireHost)=true would fail to build due to missing aspire workload

I'd put this tests pretty low on the priority list.

**Comment by eerhardt** [comment]
What is the medium-to-long-term vision for where the Azure Hosting code lives? If we intend to move it to https://github.com/Azure/azure-sdk-for-net/, it may make sense to wait until then to hook it up to automated tests.

On the Components side, my goal is to eventually move them to the Azure repo, so they can ship and service along with the Azure SDK packages.

**Comment by radical** [comment]
Combined the remaining tasks in #2689 and https://github.com/dotnet/aspire/issues/6076 into https://github.com/dotnet/aspire/issues/9576 . Closing.
