### ISSUE TITLE
Create functional tests for additional integrations

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#4741]
Split from #1566 

We are missing the EntityFramework components in our functional integration tests added in #1217. We should add them, plus any other missing components that would be valuable.

TODO:

- [ ] orleans
- [x] cosmos
- [x] dapr (@Alirexaa: moving to CommunityToolkit)
- [x] nats
- [x] seq
- [x] qdrant

Tests needed that reference these nugets too:
- [ ] Microsoft.Extensions.ServiceDiscovery
- [ ] Microsoft.Extensions.ServiceDiscovery.Abstractions
- [ ] Microsoft.Extensions.ServiceDiscovery.Dns
- [ ] Microsoft.Extensions.ServiceDiscovery.Yarp

cc @eerhardt

**Comment by eerhardt** [comment]
qdrant is done:

https://github.com/dotnet/aspire/blob/9a68b552f847caa62ebc612e4dc23160c29e36d5/tests/Aspire.Hosting.Qdrant.Tests/QdrantFunctionalTests.cs#L23-L63

**Comment by radical** [comment]
cc @sebastienros

**Comment by Alirexaa** [comment]
nats is done too:

https://github.com/dotnet/aspire/blob/9a68b552f847caa62ebc612e4dc23160c29e36d5/tests/Aspire.Hosting.Nats.Tests/NatsFunctionalTests.cs#L21-L61

**Comment by eerhardt** [comment]
CosmosDB has both EF and non-EF functional tests in [Extract EventHubs and Cosmos Tests from EndToEndTests and into Aspire.Hosting.Azure.Tests (dotnet/aspire#6538)](https://github.com/dotnet/aspire/pull/6538).

**Comment by Alirexaa** [comment]
Seq is done.

Dapr moved to CommunityToolkit.

**Comment by davidfowl** [comment]
I think this is done
