### ISSUE TITLE
[tests] More Conformance tests should use `Testcontainers`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#5254]
.. similar to how others do this.

https://github.com/dotnet/aspire/blob/44a60c18d9d77110ca0aa3b753476510e4823eb2/tests/Aspire.StackExchange.Redis.Tests/RedisContainerFixture.cs#L11-L43
https://github.com/dotnet/aspire/blob/44a60c18d9d77110ca0aa3b753476510e4823eb2/tests/Aspire.StackExchange.Redis.Tests/ConformanceTests.cs#L18-L19

Currently any tests that need to connect get skipped with `Unable to connect to server`.

- [ ] `Aspire.Microsoft.EntityFrameworkCore.Cosmos.Tests`.
- [ ] `Qdrant` (https://github.com/testcontainers/testcontainers-dotnet/issues/992)
- [x] ~~`RabbitMq`~~ (already using testcontainers, see https://github.com/dotnet/aspire/issues/5254#issuecomment-2284325181)

cc @eerhardt @sebastienros @joperezr

**Comment by eerhardt** [comment]
> Qdrant

See https://github.com/testcontainers/testcontainers-dotnet/issues/992

> RabbitMq

RabbitMQ is already using testcontainers:

https://github.com/dotnet/aspire/blob/fecfe0ac15c24de0d569714e64d255efd9a42332/tests/Aspire.RabbitMQ.Client.Tests/RabbitMQContainerFixture.cs#L34-L38

**Comment by eerhardt** [comment]
Qdrant was done with #6057.

Closing this as the only one left is CosmosDB EF tests. The value is minimal of converting the tests to use it.
