### ISSUE TITLE
WaitFor: Add health checks to remaining resources

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#5645]
With the merge of #5394 and some of the subsequent enhancements around health check integration (#5515) its now time to scale out the support for WaitFor for all of our resources. Essentially each `AddXYZ` method for a resource needs to register a health check with DI and add a matching `HealthCheckAnnotation`. Here are two examples:

**Redis**

https://github.com/dotnet/aspire/blob/1b2e640a366afd68c99b915762416774b8a9be91/src/Aspire.Hosting.Redis/RedisBuilderExtensions.cs#L36-L57

**Postgres**

https://github.com/dotnet/aspire/blob/1b2e640a366afd68c99b915762416774b8a9be91/src/Aspire.Hosting.PostgreSQL/PostgresBuilderExtensions.cs#L38-L98

# Remaining resources

## Pri0

- [x] RabbitMQ (done #5718)
- [x] MongoDB (done: #5697)
- [x] Kafka (done #5719)
- [x] MySql (done: #5705)
- [x] SQL Server (done: #5669)
- [x] Azure Cosmos DB emulator (done: #5729)
- [x] Elastic Search (done: #5725)
- [x] Oracle (done: #5734)
- [x] PgAdmin (done: #6081)

## P1

- [x] Azure EventHubs emulators (done: #6079)
- [x] Azure Storage emulator (done: #5761)
- [x] Garnet (done: #5698)
- [x] ValKey (done: #5706)
- [x] Milvus (done: #5707)
- [x] Nats (done: #5753)

Some of these resources don't have health checks and possibly won't need them but we should go through the list and very each one and create issues. We also need test coverage for the WaitFor behavior to verify that it is working as expected for each resource (example):

https://github.com/dotnet/aspire/blob/1b2e640a366afd68c99b915762416774b8a9be91/tests/Aspire.Hosting.Redis.Tests/RedisFunctionalTests.cs#L21-L68

**Comment by Alirexaa** [comment]
@mitchdenny , I could help you to completing this one.

**Comment by davidfowl** [comment]
Lets do the azure resources last.

**Comment by mitchdenny** [comment]
@Alirexaa of course! Any help is welcome with this.

**Comment by Alirexaa** [comment]
I will work on Valkey

**Comment by Alirexaa** [comment]
I will work on Milvus.

**Comment by davidfowl** [comment]
Kakfa is high on the priority list.

**Comment by davidfowl** [comment]
I sorted the list in priority order

**Comment by Alirexaa** [comment]
I will work on Elasicseach.

**Comment by Alirexaa** [comment]
I will work on Oracle.

**Comment by davidfowl** [comment]
Added PgAdmin. That will be useful to add health checks for since its so slow to start. That'll give us a visual indicator in the dashboard that it's healthy.

**Comment by Alirexaa** [comment]
I will work in nats.

**Comment by mitchdenny** [comment]
> Added PgAdmin. That will be useful to add health checks for since its so slow to start. That'll give us a visual indicator in the dashboard that it's healthy.

Is the health check primarily for the visual indicator. It's not that common that anyone will do a `WaitFor` on PGAdmin itself (example of how you would do that):

```csharp
var builder = DistributedApplication.CreateBuilder(args);
var pgsql = builder.AddPostgres("pgsql");
var db = pgsql.AddDatabase("db");
var app = builder.AddProject<Projects.MyApp>("app")
                 .WithReference(db).WaitFor(db);
pgsql.WithPgAdmin(c => {
  app.WaitFor(c); // Causes app to block loading until pgadmin is running/healthy.
});
```

**Comment by Alirexaa** [comment]
Seq and Qdrant resources are missing.

**Comment by Alirexaa** [comment]
I will work on Qdrant.

**Comment by davidfowl** [comment]
@mitchdenny did we do all of the critical resources for 9.x?

**Comment by mitchdenny** [comment]
Still have storage emulator and eventhubs emulator to do. I have a PR for storage that is close (just need to resync with latest changes).

**Comment by oising** [comment]
> Still have storage emulator and eventhubs emulator to do. I have a PR for storage that is close (just need to resync with latest changes).

I am looking at the live eventhubs conformancetests bits to allow my health check PR to be merged.
