### ISSUE TITLE
Templates 9.0 follow up work

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#6076]
Once https://github.com/dotnet/aspire/pull/6058 is merged:

- [x] ~`unsupported hosts - vs version` `Does this need to be bumped higher? Are we doing any testing of Aspire 9 with VS 17.10 or 17.11?` https://github.com/dotnet/aspire/pull/6058#discussion_r1784890643~ **UPDATE** We're happy to leave docs saying 17.12 is required but keep the template constraint set to 17.9
- [x] Update `Microsoft.Extensions.HttpResilience` version in the net9 template to net9 nuget (PR #6419)
- [x] Check if the Web template needs any updates (PR #6124)
- [x] Make sure `https://aka.ms/dotnet/aspire/third-party-notices` is valid, used in the templates
- [x] Update app host templates to use `WaitFor` where applicable
- [x] Update Service Defaults template to configure tracing for an activity source with the application name
- [x] ~#4206~ (moved to 9.1)
- [ ] [tests] Add `new-and-build` tests for `servicedefaults`, and `apphost` templates
- [x] [tests] Add test coverage for new `--aspire-version` template option

cc @DamianEdwards @joperezr

**Comment by DamianEdwards** [comment]
I ensured `https://aka.ms/dotnet/aspire/third-party-notices` works

**Comment by joperezr** [comment]
Marking as High. @DamianEdwards is going to do item 2 which is the only one required for 9

**Comment by DamianEdwards** [comment]
Moving to Backlog now that the 9.0 tasks are done.
